version: 0.0.1

# Change default server ports
server:
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001

login: daniel
password: password1

tagServiceLogin: h2a921as%21
tagServicePassword: 7as12$1as0431hjd