version: 0.0.1

server:
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001

login: daniel
password: password1

tagService:
  connector:
    type: http
    address: 127.0.0.1
    port: 9002
  login: h2a921as%21
  password: 7as12$1as0431hjd

birthdayJob:
  name: birthdayTrigger
  cron: 0 */5 * ? * * *

zodiacJob:
  name: zodiacTrigger
  cron: 0/10 * * ? * * *
