version: 0.0.1

# Change default server ports
server:
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001

httpClient:
  proxy:
    host: 127.0.0.1
    port: 9003
    scheme: http
    auth:
      username: admin
      password: password
      